## 1

```
0 0 0 0 0
0 3 3 3 3
0 3 6 6 6
0 3 6 6 7
0 3 6 6 7
```

## 2

In [8]:
import numpy as np
weights = [1, 2, 3, 4, 5]
a = 6
M = np.zeros([len(weights)+1, a+1])
M[0, 0] = 1
for i in range(1, len(weights)+1):
    for j in range(a+1):
        ways = M[i-1, j]
        if j >= weights[i-1]:  # We are able to add the current weight
            ways += M[i-1, j-weights[i-1]]
        M[i, j] = ways
print(M)

[[1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 2. 2. 2. 2.]
 [1. 1. 1. 2. 2. 3. 3.]]


## 3

We keep a vector of size $n+1$: at each cell $i$ we store the maximum possible value that the robber can reach by robbing houses up to $i$ (not including $i$).

In [22]:
m = [1, 4,  5, 2]
sol = np.zeros(len(m)+1)
sol[1] = m[0]
for i in range(2, len(m)+1):
    sol[i] = max(sol[i-1], sol[i-2]+m[i-1])
print(sol)


[0. 1. 4. 6. 6.]


## 4

In [21]:
s = [1, 3, 3, 3, 1]

def f(lower, upper):
    # Find best possible time to multiply matrices from lower to upper (including both)
    if lower == upper:
        # Base case: only one matrix, no multiplication is needed
        return 0
    best = float('inf')
    for i in range(lower, upper):
        # We try all possible places to split the product
        current = f(lower, i) + f(i+1, upper) + s[lower]*s[i+1]*s[i+2]
        best = min(best, current)
    return best

f(0, len(s)-2)

21

## 5

The subset sum problem can be reduced to the summing weights problem at target weight $a = 0$ and allowing for negative weights. Note that the solution matrix has to be large enough to accommodate the lowest possible sum of weights (which equals the sum of all negative weights) and the highest possible sum of weights (= sum of all positive weights).

## 6

If the weights are integer and we target weight $a$, we know there's at most $a+1$ possible different sums of weights that we care about. But if they are decimal, there can be up to $2^n$ different sums of weights (where $n$ is the number of weights) that are below $a$.

This can be remedied by quantizing the weights. For example, if weights are in $[0, 1]$ we can map each weight as follows: $w_i \to \text{round}(100 w_i)$. This bounds the number of possible sums, at the expense of some accuracy (we now have an approximate algorithm).